version: '3.7'

services:
  postgres-db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  web:
    build: .
    command: >
      bash -c "python /usr/src/jjj/manage.py migrate --noinput &&
               python /usr/src/jjj/manage.py runserver 0.0.0.0:8000"

    volumes:
      - .:/usr/src/jjj
    ports:
      - "8000:8000"
    env_file:
      - .docker.env
    environment:
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres-db
      DB_PORT: 5432
    depends_on:
      - postgres-db

volumes:
  postgres_data: